version: '3.8'

services:
  app:
    build: .
    ports:
      - 8080:8080
  db:
    container_name: pg_rocket
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypasswd
