version: '2'

services:

  db:
    container_name: pg_rocket
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - "db"
networks:
  test:
    external:
      name: nat
