spring:
  application:
    name: rota-rocket
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://db/mydb
    username: myuser
    password: mypass
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  mvc:
    throwExceptionIfNoHandlerFound: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
